### ISSUE TITLE
Sort podcasts by name and newest release

### ISSUE THREAD

**Issue by k3anton** [y20k/escapepod#11]
I would like to suggest a simple sorting function to make user experience easier when browsing your podcasts. 

As a user I would like to sort my podcasts by name or latest episode released.

**Comment by y20k** [comment]
Hi @k3anton , 

the list of podcasts is currently sorted like this: Podcasts that have the most recent episodes come first.

I am hesitant to add new interface elements to the app. The user interface is already very crowded. Which is a result of the basic design principle for the app: I tried to fit everything in a single screen. 

I think the easiest way to implement a sort toggle would be: add a tap-able indicator on top of the list of podcasts, that switches from "A-Z" to "Newest". This could be a single line of grey text. Example: [List Types](https://material.io/components/lists/#types).

I need to think about it. I tend to the opinion that an A-Z sort is not really necessary. Most podcasts have very distinct show art / covers. I so far have no problem finding the podcast I want to listen to. 

But that may be hugely dependent on the amount of podcasts one has subscribed to. (I have only? sixteen podcasts currently in my list.)

**Comment by ernestask** [comment]
It might be good to figure out what hides behind “as a user, I want X”. :)

Smells like having alphabetic sorting leads to selective listening with predictable positions of shows, unless I’m missing something. Not very important, I reckon, if you prefer having a sane set of defaults.

**Comment by k3anton** [comment]
> It might be good to figure out what hides behind “as a user, I want X”. :)
> 
> Smells like having alphabetic sorting leads to selective listening with predictable positions of shows, unless I’m missing something. Not very important, I reckon, if you prefer having a sane set of defaults.

Most users would prefer an alphabetic list when the list of shows they listen to becomes bigger and bigger. It's about managing your "bookmarks" if you will. 

Why do you consider this "selective listening"? Isn't selective listening when you add a podcast to your list?

**Comment by y20k** [comment]
I am closing this issue, since I do not plan to add an option for alternative sorting in the foreseeable future. In its current state the user interface is too crowded already so that I do not see how I could add the feature.

If I ever introduce a settings screen, I should re-open this issue. 

I added this issue to "[Previous discussions and feature requests](https://github.com/y20k/escapepod/issues/24)" since I have the feeling that it may come up again.

:vulcan_salute:
