### ISSUE TITLE
I have added podcast RSS and nothing happend. No error.

### ISSUE THREAD

**Issue by petrhejna** [y20k/escapepod#14]
Podcast link: https://taz0.org/bitstream/index.xml
Version: `0.7.9`

Repro steps:
- Open app,
- add link,
- top loading line indicates something happening,
- "Adding podcast." Pops up.
- Then nothing happens.

**Comment by y20k** [comment]
Hi there, 

thanks for reporting this. The feed you posted is not configured correctly, as far as I can see. The content type delivered by the server is `application/atom+xml` the **tags inside the feed are RSS** (not Atom). 

Escapepod yet needs to implement an Atom parser - which in your case would not help in your case. But that is still a thing I need to implement. 

If you are in contact to the publishers of this podcast, you may consider dropping them a not. The correct content type for RSS should be one of the following 'text/xml', 'application/rss+xml', 'application/xml'.

Sorry for not having a better answer yet.

**Comment by petrhejna** [comment]
Thanks a lot for quick and complete answer. I would only wish to have some error in the app saying that RSS feed is invalid.

**Comment by y20k** [comment]
> I would only wish to have some error

Fair point. I can initiate a [Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts) notification with an error from the download process. I full scale error dialog is a bit problematic since the whole operation runs in the background and has no knowledge of the state of the UI.

BTW. The content type of the mentioned feed seems to be fixed.

**Comment by petrhejna** [comment]
Thank you! (Yep I have notified publisher of the podcast.)

**Comment by petrhejna** [comment]
Btw, do you have some donation address? Ideally Lightning Network ;+)

**Comment by y20k** [comment]
> have some donation address

Thank you. Flattering offer. But this is just a fun project. :-)

**Comment by y20k** [comment]
The new version of Escapepod displays a short error message.
