### ISSUE TITLE
Portuguese translation not working

### ISSUE THREAD

**Issue by smarquespt** [y20k/escapepod#15]
Hi, i'm the author of escapepod Portuguese translation but despite https://github.com/y20k/escapepod/commit/ef4d1ee9941264e46a63fdd6638fddb80a693331 the translation still is'n used in the app. My system is set to Portuguese. Maybe some issue here?

regards

**Comment by y20k** [comment]
Hi @smarquespt, I am terribly sorry, but that was my fault. I had forgotten to add the Portuguese configuration. The issue will be fixed with the next release. Thank you for donating your time and energy to the project!!!

**Comment by smarquespt** [comment]
Working.
