### ISSUE TITLE
Cannot import podcast: https://www.kofein.tech/rss.xml

### ISSUE THREAD

**Issue by petrhejna** [y20k/escapepod#29]
Hi, I have issues with importing this podcast. It says:

![Screenshot_20200208-002323_Escapepod_1](https://user-images.githubusercontent.com/383295/74130919-850b6f80-4be3-11ea-8a3d-6af53d458862.png)

But podcast creators claim its ok ( https://castfeedvalidator.com/?url=https%3A%2F%2Fwww.kofein.tech%2Frss.xml ).

They say even Spotify accepted it.

Podcast Url: https://www.kofein.tech/rss.xml

Thank you for help. :)

**Comment by petrhejna** [comment]
Reference on post where I contacted creators: https://m.facebook.com/story.php?story_fbid=10215827048845539&id=1124503768&notif_t=feed_comment_reply&__tn__=-R

(In Czech only)

**Comment by y20k** [comment]
Hi @petrhejna 

the error message is misleading, sorry. Problem is the Escapepod's date parsing. It is probably too strict. 

I am using the following pattern to parse a date string within an RSS podcast feed:
`EEE, dd MMM yyyy HH:mm:ss Z`
The date that the kofein.tech feed provides is:
`Mon, 3 Feb 2020 16:00:00 CET`

I guess it is the single digit date of month that causes the hick-up. The podcasts I did test Escapepod with all add a `0`-padding to a single digit day. eg. Mon, 03 Feb 2020 16:00:00 CET

I will have a closer look into this soon.

**Comment by y20k** [comment]
Actually the `CET` might be the problematic part. The single digit day of month is not a problem.

`Mon, 3 Feb 2020 16:00:00 CET` results in a **ParseException** 

other time zone formats are working fine, e.g. `PST`, `UTC+01:00`, `GMT+01:00`, `+01:00`

**Comment by y20k** [comment]
I wrote a small patch. Escapepod will ignore the time zone, if it got a ParseException. See ([357538b](https://github.com/y20k/escapepod/commit/357538b73263581cc5a62e186271195986e44f8b)).

The patch will be part of the next release.

![Screenshot_1581331445](https://user-images.githubusercontent.com/9103935/74143625-6e711280-4bfb-11ea-8805-0380bd96f380.png)

**Comment by petrhejna** [comment]
Thank you :) :+1:
