### ISSUE TITLE
[Feed] Democracy Now! Video

### ISSUE THREAD

**Issue by y20k** [y20k/escapepod#31]
@maltfield reported this issue, using the Wiki. Since feed problems are now handled in the Issue Tracker and this one is still unsolved, I copied over his comments.

**Name of Podcast**
Democracy Now! Video

**Feed URL**
https://www.democracynow.org/podcast-video.xml

**Content Type / Status Code**
https://www.democracynow.org/podcast-video.xml

**Additional context**
The progress bar just "loads" indefinitely; no error code returned. Democracy Now! Also has an audio-only podcast that's also not working https://www.democracynow.org/podcast.xml)

**Comment by y20k** [comment]
@maltfield

I was not able to reproduce the problem you described.

**Video-Feed:** Here I get a short message - which is admittedly a bit cryptic. No indefinite progress bar. Escapepod currently does not support video podcasts.

**Audio-Feed:** On my device and in the Emulator the podcast does not make any problems.

What kind of device (and which OS version) are you using?

**Comment by maltfield** [comment]
OnePlus 3 running Lineage OS (Android 9)

**Comment by y20k** [comment]
Still experiencing the same issues? Keep in mind Video is not supported. Audio should work just fine. Cheers
