### ISSUE TITLE
Add Support for Media Notification Seekbar

### ISSUE THREAD

**Issue by msoose** [y20k/escapepod#36]
**Is your feature request related to a problem? Please describe.**
Unable to quickly scrub to a specific time using media notification.

**Describe the solution you'd like**
Add support for Android 10's support for media notification seekbar. 

**Describe alternatives you've considered**
N/A

**Additional context**
Example in screenshot showing support for this in Spotify.

![Screenshot_20200620-081247_Nova_Launcher](https://user-images.githubusercontent.com/30473690/85203907-fc59ba00-b2cd-11ea-8a4c-8322af247d9e.png)

**Comment by y20k** [comment]
Thank you. I did not even know that Android 10 offers to put a seek bar into the notification. It is actually only ~two lines of code to make this happen.

![screenshot-notification-seekbar](https://user-images.githubusercontent.com/9103935/85565155-2e04b500-b62f-11ea-9572-d7c26a076aeb.png)

**Comment by msoose** [comment]
Sweet, just built `master`, can scrub through episodes now! Thanks for adding this so quickly.
