### ISSUE TITLE
Downloads data in background but doesn't keep it

### ISSUE THREAD

**Issue by norrinr** [y20k/escapepod#37]
**Describe the bug**
There is no option to turn this on or off, and no indication that it would do this, but Escapepod was downloading podcasts using background data. It downloaded 512mb, but then when I went to play the podcast it would just crash. When I went to look in its cache folder, there were no files. So not only did it waste 512mb of my metered plan, I can't even listen to what it downloaded.

**To Reproduce**
Add a podcast, I guess, and don't disable background data for the app.

**Expected behavior**
An option to download episodes in the background, and for them to actually be kept.

**Device:**
 - Device: Sony Xperia X
 - OS: Android 9 AOSP
 - Version: 9.. kernel 4.9.189.. build PQ3A.190801.002

![dYK7dJf](https://user-images.githubusercontent.com/4553848/85795699-90bc8600-b6ed-11ea-97e9-4cadc608190b.png)

**Comment by y20k** [comment]
@norrinr 

I am sorry that the app downloaded audio in background via mobile network.

Escapepod downloads information on new podcasts (= the rss feeds) roughly every 4 hours using a background process. But I **never** should only download audio files when device is connected to WiFi. 500+ MB over just two weeks seem to be a lot of rss text files. 

I am not sure how to debug this.

But I will create a setting that will users disable background updates entirely.

**Comment by y20k** [comment]
I added a Background Refresh setting and a Download Over Mobile Network setting. That should cover the common cases for most users that need to adjust the default download behavior of the app. Thanks for bringing the problem to my attention!!

<a href="https://user-images.githubusercontent.com/9103935/86468006-ce955c00-bd36-11ea-9ec3-a9303acf365d.png"><img src="https://user-images.githubusercontent.com/9103935/86468006-ce955c00-bd36-11ea-9ec3-a9303acf365d.png" width=360></a>

**Comment by y20k** [comment]
The new version of Escapepod ([v0.9.2](https://github.com/y20k/escapepod/releases/tag/v0.9.2)) features the two new settings seen in the screenshot. It should be soon available in F-Droid and in the Play Store.

**Comment by norrinr** [comment]
Not sure what happened here...
![Screenshot_20200918-080448](https://user-images.githubusercontent.com/4553848/93619878-0b640d00-f98e-11ea-92c0-b3de7dc10b3b.png)
![Screenshot_20200918-080513](https://user-images.githubusercontent.com/4553848/93619936-19199280-f98e-11ea-987a-7586a03dc935.png)
![Screenshot_20200918-080641](https://user-images.githubusercontent.com/4553848/93619957-2040a080-f98e-11ea-8ee3-4bd789d4d0f4.png)

**Comment by y20k** [comment]
I am puzzled. I am using Escapepod on a daily basis and that never happened to me. There is one far fetched explanation, which is probably not the cause, but I will trough it out anyway.

Escapepod updates all feeds for times a day to check, if any new episodes are available. Now lets presume some crazy large RSS file - say a 10 MB file - is pulled over the course of a month. That would amount to 1200 MB for this feed alone (12MB*4*30). No episode has been downloaded at this point. That would assume a case where the app very rarely has WiFi access.

As I said, pretty unlikely scenario. If you want to find out if any of your podcasts has a LARGE RSS feed file: Trigger a manual refresh of the podcast collection - pull down the list of podcasts - and watch the download progress in the Notification drawer ("Download manager"). A large file should stand out there.

**Comment by norrinr** [comment]
As a side note, this happened while the phone was just sitting at home and plugged in. I'd left it there while out of town, and when I received the notification that my high speed data was all out, I assumed it was because my home internet was down and my xmpp client had gone haywire trying to reconnect. Instead I found it was Escapepod.

Back to the actual problem, this is probably different from the first bug you fixed. When I opened Escapepod, I had three listings instead of the expected two, and one of them was a duplicate with an episode date of back in Jan or Feb. At the same time, I got a toast popup about rss something failed. Looking at that download manager notification, it had several lines that said 'rss'. I removed the duplicate podcast with the older date, hit cancel on the download manager notification, and did a manual refresh. Unfortunately since I'm now on "2G speed", it's hard to tell if it's a big file or just slow data :).

Anyway, I think it was caught in some kind of loop trying to refresh that other entry.. it's just odd that it decided to do it that one day suddenly.

**Comment by y20k** [comment]
> One thing, though, why is it using background data if I turned off background data for it in Android?

I am not sure why that is. I need to investigate. Maybe Escapepod needs to opt in for that feature to have an effect. Meaning: It is possible, that I need some code that looks if this setting has be enabled/disabled.
