### ISSUE TITLE
[Feed] Deutsche Welle Podcasts

### ISSUE THREAD

**Issue by Knusper** [y20k/escapepod#38]
**Name of Podcast**
DW Science Unscripted

**Feed URL**
https://rss.dw.com/xml/podcast_science_unscripted

**Device:**
 - Device: Motorola G7
 - OS: Android
 - Version 9

**Additional context**
Potentially other dw feeds not working https://m.dw.com/en/media-center/podcasts/s-100977

**Comment by y20k** [comment]
@Knusper 

Thanks for reporting the issue with Deutsche Welle podcasts. Problem is, they load just fine on my test device (Android 9) and in the emulator (Android 10) fine. Is there anything special you did?

### Example screenrecording

<a href="https://user-images.githubusercontent.com/9103935/86467815-66df1100-bd36-11ea-839b-1e6607d5e065.gif"><img src="https://user-images.githubusercontent.com/9103935/86467815-66df1100-bd36-11ea-839b-1e6607d5e065.gif" width=360 /></a>

**Comment by Knusper** [comment]
The only reason I can think of, is that I installed it via fdroid and the feed is served via HTTPS - I read recently that antenna pod via fdroid has also similar problems: https://f-droid.org/2020/05/29/android-updates-and-tls-connections.html

**Comment by Knusper** [comment]
So it just happened that I got an update from my mobile phone manufacturer and with this new update it is be working.
