### ISSUE TITLE
Add Access to Show Notes

### ISSUE THREAD

**Issue by PapistPenguin** [y20k/escapepod#4]
Hello. Many of the podcasts I listen to come with show notes. Would it be possible to add access to them?

**Comment by y20k** [comment]
two ways to get to the show notes:
- long press on an episode in the list will display the show notes
- simple tap on the show art in the expanded player will display show notes

**Comment by PapistPenguin** [comment]
Oh, I did not realize that. Thank you!

**Comment by y20k** [comment]
the app has some more long-press features ;)
