### ISSUE TITLE
Website doesn't work on Firefox

### ISSUE THREAD

**Issue by xerus2000** [y20k/escapepod#43]
Instead, I get this:
![image](https://user-images.githubusercontent.com/13354331/89169177-2d403680-d57e-11ea-94c8-15bae03295dc.png)
https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?as=u&utm_source=inproduct

**Comment by y20k** [comment]
the page is http-only. it is hosted on a cheap plan that does not allow manual installation of certs.

**Comment by xerus2000** [comment]
Ah ok, didn't know http-only sites still existed ^^ apparently, the DDG Privacy Essentials add-on disallows http completely, so I'll see what can be done there.

**Comment by y20k** [comment]
:wink:
