### ISSUE TITLE
[Feed]

### ISSUE THREAD

**Issue by books516** [y20k/escapepod#53]
**Name of Podcast**
Building a Story Brand

**Feed URL**
https://www.stitcher.com/podcast/storybrand/building-a-story-brand-with-donald-miller-helping-you-clarify.

Sorry, not sure exactly how to find feed

**Content Type / Status Code**
Only if you find the time to look it up: Content Type and Status Code of a feed can be found in the network tab of the developer tools in your web browser.

**Device:**
 - Device: [e.g. OnePlus 5]
 - OS: [e.g. Lineage OS 16.0]
 - Version [e.g. v1.0]

**Additional context**

**Comment by y20k** [comment]
try this feed 
https://storybrand.libsyn.com/rss
