### ISSUE TITLE
Proprietary dependency: com.idescout.sql:sqlscout-server:4.1

### ISSUE THREAD

**Issue by relan** [y20k/escapepod#64]
**Describe the bug**
https://www.idescout.com/maven/repo/ repository with proprietary libraries prevents Escapepod 1.0.0 from being on F-Droid.

**To Reproduce**
See [build.gradle](https://github.com/y20k/escapepod/blob/master/build.gradle#L23) and [app/build.gradle](https://github.com/y20k/escapepod/blob/master/app/build.gradle#L88).

**Expected behavior**
No custom Maven repositories and proprietary libraries.

**Screenshots**
n/a

**Device:**
n/a

**Additional context**
F-Droid inclusion policy: https://f-droid.org/docs/Inclusion_Policy/

**Comment by y20k** [comment]
Thanks for the hint. I will remove the dependency.

**Comment by y20k** [comment]
@relan will I need to publish a new release? Or will the change in https://github.com/f-droid/fdroiddata/commit/f0d1faf755d416905393fd56466a14d01904c47e take care of it, so that the current version will be published on F-Droid?

**Comment by relan** [comment]
The new version will be added automatically once you tag v1.0.1.
