### ISSUE TITLE
App crash when adding podcast.

### ISSUE THREAD

**Issue by prashasth-nair** [y20k/escapepod#66]
App version: 1.0.2
Android version: 9
The app crash when adding a new podcast. It shows adding podcast then the app crash.

**Comment by y20k** [comment]
Hi @prashasth-nair 
Thank you for reporting this problem. I have a suspicion, of what the problem might be. It would be super great if you could share the porcast that caused the crash. Or can you confirm that only some podcasts seems to cause the crash.

**Comment by prashasth-nair** [comment]
I think few podcast cause this problem i was trying to add "Hacking the Hustle" podcast then the app crashes.

**Comment by y20k** [comment]
In the meantime I experienced the crash too. It is caused when the app wants to display an error message. In my case there was a problem with the podcast cover.

**Comment by y20k** [comment]
I found the error and the cause for the crash. It was the error message, that is displayed, when trying to add an "incompatible" podcast. I have [fixed](https://github.com/y20k/escapepod/commit/a10cf94e527b31fe886b944d870d818b5026a14b) that for the next release.

But this will not help you :-/ => When trying to add [Hacking the Hustle](https://anchor.fm/s/35ea328/podcast/rss) podcast, the app will not crash, but it will will not add the podcast either. Just the error message will be shown correctly.

Hacking the Hustle is currently delivered as `audio/x-m4a`, which is not yet supported.

**Comment by prashasth-nair** [comment]
Ooh No problem. Thanks for solving the crash.
