### ISSUE TITLE
Import re-appears every restart of Escapepod

### ISSUE THREAD

**Issue by giwu37** [y20k/escapepod#67]
I upgraded via F-Droid to 1.01 and later to 1.02 via APK-Installation. I had a backup of my podcasts made with OPML-Export.

Import that file worked with no problem in 1.01 and 1.02. But in both versions the import file dialog pops up now increasing the count every time.

**To Reproduce**
1. Import OPML-File
2. Wait for download
3. Quit
4. Restart Escapepod

**Expected behavior**
Import ends after downloading imported podcasts.

**Device:**
 - Device: Moto G7plus
 - OS: Android 10 Sec Level Feb 2021

**Comment by y20k** [comment]
Hi, good evening @giwu37 

Thanks for reporting this bug. I tried to reproduce the problem, but I was not able to do so. This is what I did. 

1. Start Escapepod
2. Escapepod > Settings > Export OPML > Select Save Location
3. Home screen > Escapepod (i) > Storage & cache > Clear storage
4. Home screen > Escapepod (i) > Force stop
5. Escapepod > Settings > Import OPML > Select Import Location
6. Import
7. Quit Escapepod via task switcher
8. Optional: Home screen > Escapepod (i) > Force stop
9. Start Escapepod
10. Imported podcasts are shown - no import dialog

Does your "procedure" here differ in any way?

**Comment by giwu37** [comment]
No, my procedure does not differ except that I didnt force the stop of the app.
And even "worse": I cant reproduce it right now. I have 1.01 from F-Droid running to get the automatic update to 1.02 and it works now.
So I close this and re-open if there is more to come.

**Comment by y20k** [comment]
I found a way to reproduce the problem. This should make it easier to find/fix the bug.

1. open Escpapepod
2. go to Settings
3. Import OPML
4. Cancel the Import
5. go to Settings
6. go back to Player without doing anything
