### ISSUE TITLE
Start playing another podcast while one is already playing will jump the new track forward

### ISSUE THREAD

**Issue by windsurfer** [y20k/escapepod#72]
**Describe the bug**
If I select "Start now" on a podcast while one is already playing, the new podcast will start playing from the position the old one was at.

**To Reproduce**
1. Play a podcast and jump forward a little bit. Don't pause it.
2. Tap on another podcast to play it. A prompt will ask you if you want it to start now.
3. Select start now and notice that it starts playing from the same position the first podcast was at

**Expected**
The new podcast should start at the beginning. 

**Device:**
 - Device: Fxtec Pro1
 - OS: Lineage OS 17.1
 - Version 1.0.3 (f-droid)

**Comment by y20k** [comment]
@windsurfer 

Thank you for the bug report. I can reproduce the problem. I observed some inconsistencies with the saving of playback progress myself, but I was never able to really pinpoint the problem. 👍

**Comment by windsurfer** [comment]
This is fixed in the latest f-droid releasse 😎
