### ISSUE TITLE
Can't download episodes from the past

### ISSUE THREAD

**Issue by therealrobster** [y20k/escapepod#77]
**Describe the bug**
I want to download say episode 1.  The podcast has say 100 episodes.  So I only see episode 100.  When I press Older Episodes, I only get 4, so I get episodes 96-100.  I press it again and it closes the 4.  I need to download all the older episodes.

**Device:**
 - Device: Google Pixel 1
 - OS: Lineage OS sailfish 10
 - Version [ Escapepod v1.0.4]

**Comment by y20k** [comment]
Sorry for the short answer. But this issue may be a duplicate. See #18
