### ISSUE TITLE
Multiple podcast in queue

### ISSUE THREAD

**Issue by ghost** [y20k/escapepod#81]
Please give the option of add multiple podcast in queue. For now escapepod only have 1 podcast in the queue feature. But multiple podcasts in the queue will be very useful for many user.
Thank you.

**Comment by y20k** [comment]
Thanks for suggesting this. But this is not a planned feature. I do not want to implement a queue management. As soon as we have more than one Episode that is in the queue, the app would need a user interface to a organize the queue: Add, Rearrange, remove, more info about the queue items. ... I want Escapepod to stay a single screen app.
