### ISSUE TITLE
Corrupted Date after Update

### ISSUE THREAD

**Issue by giwu37** [y20k/escapepod#88]
![Screenshot_20210818-215135](https://user-images.githubusercontent.com/11301959/129971819-437d4875-8a53-4be7-a33e-3a0ca4aed333.png)
**Describe the bug**
After updating the feeds the date of some feeds is corrupted. Nevertheless the episodes are downloaded. But normally these are older episodes.

**Screenshots**
Screenshot added. Especially the year makes it clear.

**Device:**
 - Device: Moto G7 plus
 - OS: Vanilla Android
 - Version: 10

**Comment by y20k** [comment]
Hi @giwu37 
Thanks for reporting this!!! What you are describing is a known problem. I / we are not 100% sure what causes it. Head over to #76 to find out more.
