### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by kpd001** [y20k/escapepod#9]
Since upgrading to version 0.7.4 the app is crashing when launching.

On the newest security update of Android 10 on a Pixel, storage permission is allowed

Logcat below:

> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: FATAL EXCEPTION: main
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: Process: org.y20k.escapepod, PID: 9936
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/3552 from pid=9936, uid=10251 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at a.a.a.d.g.a(SourceFile:4)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at a.a.a.b.a.a(SourceFile:3)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at a.a.a.i.a(SourceFile:21)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at androidx.lifecycle.LiveData.a(SourceFile:6)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at androidx.lifecycle.LiveData.b(SourceFile:5)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at androidx.lifecycle.LiveData$b.a(SourceFile:10)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at androidx.lifecycle.LiveData$LifecycleBoundObserver.a(SourceFile:5)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at g.m.l$a.a(SourceFile:3)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at g.m.l.a(SourceFile:21)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at androidx.lifecycle.LiveData.a(SourceFile:15)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at org.y20k.escapepod.PodcastPlayerActivity$g.a(SourceFile:32)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.support.v4.media.MediaBrowserCompat$b$a.onConnected(SourceFile:3)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.media.browse.MediaBrowser$6.run(MediaBrowser.java:603)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 10-12 09:20:25.538  9936  9936 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by y20k** [comment]
Oh that is bad. I do not have an Android 10 device at hand. I will try to find the problem using an emulator. Did you do anything special before updating from v0.7.3 to v0.7.4? Like switching from the PlayStore version to the F-Droid one?

**Comment by y20k** [comment]
BTW. The only way to fix the problem for you would only be: delete data and re-import OPML - see [Troubleshooting](https://github.com/y20k/escapepod/wiki/Troubleshooting#option-2-delete-application-data) Sorry.

**Comment by y20k** [comment]
I tried to reproduce the problem using the Emulator running Android 10. I tried the following steps.

1. Install v0.7.3 from F-Droid
2. start Escapepod
3. add a podcast
4. start playback / stop playback
5. Exit / Quit Escapepod
6. Update to v0.7.4 from F-Droid
7. start Escapepod
8. resume playback

Sadly (or gladly?) no crash so far. Any idea, which steps I might need to take to repoduce the problem?

**Comment by kpd001** [comment]
Thanks for the response, a bit more info: 

I have only been using the F-Droid version

I made a copy of the org.y20k.escapepod folder (org.y20k.escapepod.bak) and then cleared the app data. I was able to import an OPML without issue. If I replace the "collection.json" file from my backup in the "collections" folder it crashes at launch again. Seems something in that configuration is causing an issue.

The steps you've listed above are accurate, only thing I have done different is upgrade to the Android October secuirty patch between steps 5 and 6 (after quitting Escapepod, before upgrading to v0.7.4)

**Comment by y20k** [comment]
When I manually copy over `collection.json` I get the same crash. `collection.json` stores among other things URIs describing the downloaded image and audio files. The access permissions on those URIs seem to be tied to a specific installation of an app (`pid` & `uid`). Under normal circumstances an update does not change those IDs.

But if we manually intervene and copy over a `collection.json` from **another** installation, we get a SecurityException. So far it makes sense to me. One should not manually edit files in `/Android/data/...`. But I still wonder how the crash was triggered the first time you experienced it.

**Comment by y20k** [comment]
Just a speculation: Maybe the Android auto backup / restore feature did copy over the wrong `collection.json`. But you are probably not running Google Play Services on your device, right? Anyway I excluded `collection.json` from auto backup - just to be safe for users running Play Services.

**Comment by kpd001** [comment]
Sorry for the delay. 

I am running Google Play Services and as far as I can tell the OTA update applied without any issues.  Really not sure what the root cause of the issue is but if it comes back up I'll let you know

**Comment by y20k** [comment]
I implemented a check that should prevent a crash like you described. I will close this issue. Feel fre to re-open it, if the problem persists. And: Thanks for your help!!

**Comment by y20k** [comment]
Actually a just got another instance of the bug. But I think I have a solution. The fix will be part of v0.7.8. Stay tuned.

**Comment by kpd001** [comment]
Again, sorry for the delay:

I'm still on v0.7.7 but this bug popped up again after not using the app for about a week. If another log would help you let me know and I can pull it.

Will re-importing the OPML be required to get up and running again? Or should v0.7.8 be able to handle whatever weirdness is happening with the collection.json file without having to start fresh?


Thanks for looking into this!

**Comment by y20k** [comment]
I am really sorry. But you will have to wait for v0.7.8 (to be released on Wednesday - probably) and then re-import the podcasts via OMPL. 

On the positive side... I think, I found the underlying issue. Escapepod uses [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager) to fetch images and audio files. DownloadManager hands over Uris through which Escapepod can access those media files. I now found out(*) that those specific Uris are not guaranteed to work over a longer period of time. I use Escapepod on daily basis and on my (only) test device I never experienced the problem. But I was able to reproduce the issue simply by deleting some media files manually.

Anyway What Escapepod now does is, it makes a copy of a download, as soon as it finishes. And it stores an Uri to that copy instead of the Uri that came from DownloadManager. So I hope, from now on going forward the issue should be solved

(*) [How to Consume Content From a Uri (CommonsWare Blog)](https://commonsware.com/blog/2016/03/15/how-consume-content-uri.html)

**Comment by y20k** [comment]
[v0.7.8](https://github.com/y20k/escapepod/releases/tag/v0.7.8) is out. Could you do me a favor and do the following?

1. Make a copy of the OPML file (just in case)
2. Install v0.7.8 though your normal update channel (probably Play Store or F-Droid)
3. Open the app

I am interested if the app still crashes. My guess / hope is, that the app will start normally. The podcast covers may not be present in your case. That should change with the next automatic update. Automatic updates are scheduled every four hours. And therefore I would ask you to:

4. Open the app again four hours later.

Sorry, but I had to somewhat blindly code a solution here, because I was not 100% able to reproduce the issue.

**Comment by kpd001** [comment]
Unfortunately (or fortunately I suppose) I have not been having any issues with crashing. I'll try letting the app sit for a week and see if the issue comes up again as it did in earlier versions
