### ISSUE TITLE
Podcast download does not work/octet-stream error

### ISSUE THREAD

**Issue by giwu37** [y20k/escapepod#93]
**Describe the Bug**

After switching to a new phone two downloads are not working any more. 

**To Reproduce**
Just update and you get an error.

**Expected behavior**
Download of the podcast episode.

**Screenshots**
![Screenshot_20211119-230618](https://user-images.githubusercontent.com/11301959/142742139-6432c063-f881-4398-99db-c6231c887549.jpg)

**Device:**
 - Device: OnePlus CE 5G
 - OS: Oxygen OS
 - Version 11.0.9.9

First time I imported via OPML. To reproduce the error I deleted all data from Escapepod and subscribed only "0630" from WDR. The bug appeared.
Podcasts that 'work'
WDR Hörspielspeicher
0630 Daily news show (also WDR)

Update: I tried some more WDR-Podcast (random pick). WDR 2-5 feeds are buggy, EinsLive (WDR 1) is not.

**Comment by y20k** [comment]
Thanks for reporting this problem!! 
I am aware of the issue. Some podcasts are delivered with an incorrect file encoding (here: `application/octet-stream`). Currently the app only supports audio files that are delivered with one of the [mime types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) defined [here](
https://github.com/y20k/escapepod/blob/9ffee4fd2c704fd7295f612c6ed030c74e87b7d5/app/src/main/java/org/y20k/escapepod/Keys.kt#L149). I need to think of a way to reliably identify file types. I am a bit hesitant to only bet on file extensions for that.
