### ISSUE TITLE
EscapePod blocks headset control from other player

### ISSUE THREAD

**Issue by giwu37** [y20k/escapepod#94]
**Describe the bug**
I use two podcast players on my phone. AntennaPod and EsacapePod. If I start a Podcast with AntennaPod on BT Headset and pause it with the headset it will start EscapePod when I press play again.

**To Reproduce**
1. Start Podcast in AntennePod
2. Press Pause on BT Headset
3. Press play again
4. Start EscapePod

**Expected behavior**
BT Headset controls the last used player.

**Device:**
 - Device: OnePlus Nord CE 5G
 - OS: Oxygen OS
 - Version 11.0.9.9

**Additional Infos**
I just had this effect again. I was listening to AntennaPod, pause it, and the it restarted EscapePod. This also happens if I "kill" EscapePod via the X-Symbol in the notification area.
[Update] It's always the described way, never the other way that AntennaPod steels control from EscapePod.
BTW Both player connect to the notification area. And I can choose them by swiping left or right. Noone of them ever disappears from notification area.

**Comment by giwu37** [comment]
I must confess that it looks like its not EscapePods problem. All other players seem to "overwrite" AntennaPod (EscapePod, ARD Audiothek, DLF Audiothek). I will do some more tests and report.

**Comment by y20k** [comment]
Thanks for looking into this! And Cheers

**Comment by giwu37** [comment]
Sorry for the long delay. But I can confirm now that EscapePod has **nothing to do with it.** It's AntennaPod that "loses" the connection to the BT Headset Controls (sometimes immediatly). Sorry for the wrong suspect. ;-)
But I found another bug while investigating on this one and will report that in an extra thread.
